# -*- coding: utf-8 -*-
"""Gustavo Duarte - 0050017151.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H0jMTQkrqabhfa9P_MsXyQBonnS9xGPl
"""

import pandas as pd
import numpy as np

alunos = pd.Series(['Alun1','Alun2','Alun3','Alun4','Alun5','Alun6'])

alunos[:2]

alunos[2:4]

al = pd.DataFrame(alunos, columns=["Aluninhos"])

file = pd.read_excel('https://raw.githubusercontent.com/salgado/lasalle.2020.1.gc/master/dados_abertos.xlsx')

table = pd.DataFrame(file)

table.describe

table[table['Setor']=='Tecnologia']

table.sort_values(by='Titulo')

